### ISSUE TITLE
Update to TSLint 5.13

### ISSUE THREAD

**Issue by madelson** [JoshuaKGoldberg/TSLint.MSBuild#102]
I'm assuming that the current 5.10 package runs TSLint 5.10. I'd like 5.13 so I can use the ignore-rhs rule.

**Comment by JoshuaKGoldberg** [comment]
Agreed, that'd be great to release. Accepting PRs!

**Comment by madelson** [comment]
@JoshuaKGoldberg happy to make a PR but I'm not sure what's required. The NuGet package in question seems to be `tslint`, whose project site is the main tslint project. However, they told me that they weren't familiar with the NuGet release (see https://github.com/palantir/tslint/issues/4586#issuecomment-474788519).  Any suggestions for how to proceed? It seems likely to me that no code changes are required, only for an owner to publish.

**Comment by JoshuaKGoldberg** [comment]
Oh, pardon me, I didn't notice this is in the TSLint.MSBuild repository! You're looking for https://github.com/joshuakgoldberg/tslint-nuget. I just updated it to 5.14.0 and am publishing now.
