### ISSUE TITLE
TSLint.MSBuild -> EsLint.MSBuild is coming?

### ISSUE THREAD

**Issue by barshopen** [JoshuaKGoldberg/TSLint.MSBuild#105]
So [Roadmap: TSLint → ESLint.](https://github.com/palantir/tslint/issues/4534) happened and now TSLint is deprecated. Is TSLint.MSBuild working with ESLint? Is there an easy transition between the two, to get MSBuild for it? Or is there a plan to make one?
Thanks.

**Comment by JoshuaKGoldberg** [comment]
Ha! Interesting idea. All yours if you want 😃. I have no plans on making either. This old repository will not adopt to use ESLint.

Feel free to copy code from here and/or tag me for review of it's helpful!
