### ISSUE TITLE
Cannot read configuration when encoding is UTF8 with BOM.

### ISSUE THREAD

**Issue by dufrannea** [JoshuaKGoldberg/TSLint.MSBuild#17]
Hi,

My tslint.json is using the UTF8 with BOM encoding, and fails to be read using fs.readFile and JSON.parse ([see here](https://github.com/JoshuaKGoldberg/TSLint.MSBuild/blob/master/src/Folder.ts#L92)).

This is a [choice made by nodejs](https://github.com/nodejs/node-v0.x-archive/issues/1918), that fs.readFile* does not remove BOM when present. I think it might be a good idea to strip it by default using for example the [strip-bom](https://github.com/sindresorhus/strip-bom) library.

I'd be glad to do that if you consider it as useful.

Cheers !

**Comment by JoshuaKGoldberg** [comment]
Yes, please do! That would be useful.

Please do use the code inline rather than use the npm module. No need for that dependency in the build process.

**Comment by JoshuaKGoldberg** [comment]
Resolved by #18.
