### ISSUE TITLE
Create a global override of issues severity.

### ISSUE THREAD

**Issue by dufrannea** [JoshuaKGoldberg/TSLint.MSBuild#19]
Hi, 

Right now when using TSLint.MSBuild, all issues are reported as errors. I understand this is a tslint problem (palantir/tslint#345) that will be fixed at some point, but right now this issue prevents me from using tslint.

Most of the issues raised by other linters/analysers in my projects are warnings, and I do not want errors to show up for spacing issues.

There might be another way of doing this I am not aware of, if not, would you consider adding a msbuild property (something like TSLintTreatErrorsAsWarnings) for this purpose ?

Cheers

**Comment by JoshuaKGoldberg** [comment]
Having a build property for this is a good idea.

It would be better to have it as something like `TSLintErrorsSeverity`, with a default to error severity. That way we could also treat them as logs, etc.

**Comment by dufrannea** [comment]
I agree it'd be better to have a parameter for severity.
I would be glad to look into this if you want.
Let me know !

**Comment by JoshuaKGoldberg** [comment]
:) Please do!

**Comment by JoshuaKGoldberg** [comment]
https://blogs.msdn.microsoft.com/msbuild/2006/11/02/msbuild-visual-studio-aware-error-messages-and-message-formats/
