### ISSUE TITLE
Unknown Severity 'warningUnusedImport'

### ISSUE THREAD

**Issue by stephen-nba** [JoshuaKGoldberg/TSLint.MSBuild#48]
Hi

I am getting the following error:

`1>  Error running TSLint!
1>Error : Unknown error severity: 'warningUnusedimport'.`

Using TSLint.MSBuild.0.4.1, tslint.3.15.1. 

Also, 

`Starting TSLint runner.
1>  Setting '--config' to 'tslint.json'.
1>  Setting '--error-severity' to ''.
1>  Setting '--exclude' to ''.
1>  Setting '--file-list-file' to 'TSLintFileList-project.txt'.
1>  Setting '--files-root-dir' to 'C:\[folder]\project'.
1>  Setting '--rules-directory' to ''.`

Any ideas?

**Comment by JoshuaKGoldberg** [comment]
I'll need a little more information than that to debug your issue. What version of TSLint.MSBuild are you running? Can you provide a minimum-sized reproduction of the issue?

Getting a severity `warningUnusedimport` looks like two potential problems:
* You're not running on the latest TSLint.MSBuild
* You're provided invalid strings to the runner

**Comment by stephen-nba** [comment]
Hi

Thanks for the reply. I was using 0.4.1, but now I've just updated to 1.0.0 beta 1, and it all works sweet. 

Thank you very much!
