### ISSUE TITLE
Green squiggles for warnings

### ISSUE THREAD

**Issue by stephen-nba** [JoshuaKGoldberg/TSLint.MSBuild#49]
Hi 

Is it possible for the warnings to show up in the editor with squiggles on the place where it occurs? I'm not sure of the exact terminology here but for example if I use a Rosyln analyser it will show up as a warning and green squiggle on the code where the warning happens. Is it possible to do that with TSLint?

Cheers

**Comment by JoshuaKGoldberg** [comment]
Yes. That would be specific to your editor. See the list of integrations at https://github.com/palantir/tslint#tslint.

**Comment by stephen-nba** [comment]
My editor is Visual Studio.

Are you saying I need to use the Web Analyzer extension for Visual Studio and not your MSBuild integration? I already tried the Web Analyzer extension and it didn't seem to show any squiggles. You can see over here it is on the todo list but the tool hasn't seen any changes since February and I doubt it will get done:

https://github.com/madskristensen/WebAnalyzer/blob/master/CHANGELOG.md

I was keen on your MSBuild integration so it runs on a CI build server as well. I guess I'm not asking about TSLint integration, i'm asking about TSLint.MSBuild integration with Visual Studio. 

Hope that makes sense!

**Comment by JoshuaKGoldberg** [comment]
It does!

TSLint.MSBuild is basically just a .targets file that you can reference in your .csproj. It's not made to provide any intellisense during editing; all it does is connect your MSBuild logic to a Node executable to run TSLint.

If you want the squigglies in your editor that's up to your editor's extension(s) to provide. In the case of Visual Studio that would be Web Analyzer. I don't believe WA adds any build logic to solutions or projects, so (correct me if I'm wrong) getting TypeScript linting in both your CI and edit-time requires both TSLint.MSBuild and Web Analyzer.

**Comment by stephen-nba** [comment]
Hmmm ok I'm not seeing any squiggles with Web Analyzer but now it looks like it is deprecated with ASP.Net Core Tooling with 'Web Code Analysis'. Which also doesn't show any squiggles. 

I'm not really sure where to go from there but either way it doesn't seem to be your problem, thanks for your help so far!
