### ISSUE TITLE
How to use TSLintCli property?

### ISSUE THREAD

**Issue by brettjacobson** [JoshuaKGoldberg/TSLint.MSBuild#67]
I've tried every permutation I could on the TSLintCli property to try and make it use the tslint that is installed in our node_modules folder, with no luck.  What do you think the magic syntax should be to force it to use tslint acquired through npm instead of using a NuGet package to download TSLint into the packages folder?

**Comment by brettjacobson** [comment]
Never mind looks like I had something else stupid broken that was completely preventing it from running.
<TSLintCli>node_modules/tslint/bin/tslint</TSLintCli>
works fine.
Would it be a good idea to make this the highest priority check, before digging through the Packages folder?

**Comment by JoshuaKGoldberg** [comment]
Sure, that seems reasonable. PR?

**Comment by brettjacobson** [comment]
I'm naive when it comes to git and PRs.  I'll see if I can figure out how to do them this week.

But it looks like the magic to add to the .targets is this (before the others):
`<TSLintPotentialCli Include="$(ProjectDir)node_modules/tslint/bin/tslint" />`
