### ISSUE TITLE
Support changing the formatter

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/TSLint.MSBuild#69]
See #66. The user may want `--formatter json` instead `--formatter msbuild`.

**Comment by brettjacobson** [comment]
or VSO :)

I think locally we would want msbuild format so its nice to use in Visual Studio IDE, while when running on the build server VSO might be a preferred format.

And then we'd also want the json format to feed into SonarTS later.

I think if someone wanted to use a custom formatter, I think TSLintExtraArgs would allow to specify the folder that pointed to a custom formatter.

I've begun researching a "multi-formatter", but I've made little progress.

**Comment by JoshuaKGoldberg** [comment]
This almost feels like it should be a native part of TSLint. Perhaps if you pass multiple `--formatter` args in, it should use all of them?
