### ISSUE TITLE
TSLintErrorSeverity - How do I make all errors appear as warnings?

### ISSUE THREAD

**Issue by Swellenator** [JoshuaKGoldberg/TSLint.MSBuild#82]
In Visual Studio all the tslint issues are listed as errors. The build isn't reported as being failed, but it would be cleaner if the list of issues were treated as warnings. 

In VS Code I have set a property like '"tslint.alwaysShowRuleFailuresAsWarnings": true' and I found TSLintErrorSeverity here in an old commit - but it is no longer there! 

I realise I can set the severity of each rule, but then i would have to include all the extended rules in my tslint.json. 

Is there still a way to get all the errors to show as warnings in Visual Studio?

**Comment by JoshuaKGoldberg** [comment]
Hi @Swellenator - this repository is just for the MSBuild TSLint runner, not IDE integrations. You're probably using [WebAnalyzer](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.WebAnalyzer) or [TypeScript Analyzer](https://marketplace.visualstudio.com/items?itemName=RichNewman.TypeScriptAnalyzer) to get error/warning reporting in Visual Studio. 

As per [palantir.github.io/tslint/usage/configuration](https://palantir.github.io/tslint/usage/configuration), try setting `"defaultSeverity"` to `"warning"` in your configuration file?

**Comment by Swellenator** [comment]
Hi @JoshuaKGoldberg, in fact I am just using your tool, but as you are using the msbuild formatter for tslint it outputs the text which is automatically consumed by Visual Studio. Interestingly the documentation here:

https://palantir.github.io/tslint/formatters/msbuild/

States that the output will always be warnings, but if you look closer I think they have changed it to output the severity of each rule.

Setting the defaultSeverity only affects the rules in that file, not the inherited ones, so it's not feasible to write out all the rules inherited just to update the severity of them. 

I guess I'll wait and see what happens over here:

https://github.com/palantir/tslint/issues/2569

Cheers
