### ISSUE TITLE
Some fixes for the package

### ISSUE THREAD

**Issue by isc30** [JoshuaKGoldberg/TSLint.MSBuild#85]
Hi, I thought the package was unmaintained and we needed some urgent changes on it for our application so I forked it and added some fixes (improved error messages, dot escape, quotes in the command, fix output file) etc.

The main problem was:
* Build
* Get the TSLint errors
* Build again
* No errors (because of the output file)

In case you like those changes I can create a PR for you.
Check the changes here: https://github.com/JoshuaKGoldberg/TSLint.MSBuild/compare/master...isc30:master

**Comment by JoshuaKGoldberg** [comment]
Hey, thanks for the changes! The package is certainly maintained; I haven't had a need to push any changes in a while. _(thanks for the reminder to triage GH issues, though!)_

Could you file separate issues & send pull requests for the issues you came across? It's a little hard to understand just from that one plain diff what the contexts behind all your changes are.

**Comment by isc30** [comment]
Sure! I will, thanks 👍

**Comment by isc30** [comment]
I hope you liked those changes, they help a lot when using this package on daily basis
Thanks a lot!

**Comment by JoshuaKGoldberg** [comment]
@isc30 these changes made my day 💖. Thanks so much!
