### ISSUE TITLE
Doesn't work with Visual Studio 2017 without overridding TSLintCli

### ISSUE THREAD

**Issue by cdhawan** [JoshuaKGoldberg/TSLint.MSBuild#98]
In VS2017 packages can be restored to "%UserProfile%\.nuget\packages" based on configuration or new csproj format.

In this case TSLintCli is path is not resolved, until we override it. Changing the last search path to following help. 

      <TSLintPotentialCli Include="$(MSBuildThisFileDirectory)..\..\..\tslint\$(TSLintVersion)\tools\node_modules\tslint\bin\tslint" /> 

Can this project be updated to uptake this ?

**Comment by JoshuaKGoldberg** [comment]
Thanks for pointing this out! A PR to add this in would be great, yes please!

**Comment by JoshuaKGoldberg** [comment]
Released as 1.4.2: https://www.nuget.org/packages/TSLint.MSBuild/1.4.2 🚀
